name: dadinho
description: Um novo projeto Flutter.
# A linha a seguir impede que o pacote seja publicado acidentalmente no pub.dev usando `flutter pub publish`.
# Isso é preferível para pacotes privados.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

# O seguinte define a versão e o número de compilação para o seu aplicativo.
# Um número de versão tem três números separados por pontos, como 1.2.43,
# seguido por um número de compilação opcional separado por um +.
# Tanto a versão quanto o número de compilação podem ser substituídos no flutter
# build, especificando --build-name e --build-number, respectivamente.
# No Android, build-name é usado como versionName, enquanto build-number é usado como versionCode.
# Leia mais sobre a versão do Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString, enquanto build-number é usado como CFBundleVersion.
# Leia mais sobre a versão do iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# No Windows, build-name é usado como as partes major, minor e patch
# do produto e versões de arquivo, enquanto build-number é usado como sufixo de compilação.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# As dependências especificam outros pacotes que seu pacote precisa para funcionar.
# Para atualizar automaticamente as dependências do seu pacote para as versões mais recentes,
# considere executar `flutter pub upgrade --major-versions`. Alternativamente,
# as dependências podem ser atualizadas manualmente alterando os números de versão abaixo para
# a versão mais recente disponível em pub.dev. Para ver quais dependências têm versões mais recentes disponíveis,
# execute `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

# O seguinte adiciona a fonte Cupertino Icons ao seu aplicativo.
# Use com a classe CupertinoIcons para ícones no estilo iOS.
cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# O pacote "flutter_lints" abaixo contém um conjunto de lints recomendados
# para incentivar boas práticas de codificação. O conjunto de lints fornecido pelo pacote é
# ativado no arquivo `analysis_options.yaml` localizado na raiz do seu
# pacote. Consulte esse arquivo para obter informações sobre a desativação de regras de lint específicas
# e ativação de outras adicionais.
flutter_lints: ^2.0.0

# Para obter informações sobre a parte genérica do Dart deste arquivo, consulte a
# seguinte página: https://dart.dev/tools/pub/pubspec

# A seguinte seção é específica para pacotes Flutter.
flutter:

  # A linha a seguir garante que a fonte Material Icons esteja
  # incluída no seu aplicativo, para que você possa usar os ícones na
  # classe Material Icons.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Um ativo de imagem pode se referir a uma ou mais "variantes" específicas de resolução, consulte
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Para detalhes sobre como adicionar ativos de dependências de pacotes, consulte
  # https://flutter.dev/assets-and-images/#from-packages

  # Para adicionar fontes personalizadas ao seu aplicativo, adicione uma seção de fontes aqui,
  # nesta seção "flutter". Cada entrada nesta lista deve ter uma
  # chave "family" com o nome da família da fonte e uma chave "fonts" com um
  # lista que fornece o ativo e outros descritores para a fonte. Por exemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalhes sobre fontes de dependências de pacotes,
  # consulte https://flutter.dev/custom-fonts/#from-packages
